[font]
size = 16.0

[font.bold]
family = "CaskaydiaCove NFM"
style = "Medium"

[font.bold_italic]
family = "CaskaydiaCove NFM"
style = "Heavy Italic"

[font.italic]
family = "CaskaydiaCove NFM"
style = "Italic"

[font.normal]
family = "CaskaydiaCove NFM"
style = "Regular"

[window]
blur = true
decorations = "Buttonless"
opacity = 0.9

[window.padding]
x = 5
y = 5
