name: "darwin nix build"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-14-arm64
    steps:
    - uses: actions/checkout@v4
    - name: Install nix
      uses: DeterminateSystems/nix-installer-action@v16
    - uses: extractions/setup-just@v2

    - name: Build
      working-directory: ./config/nix-config
      run: just build zeus
